feat(ci): update format-and-lint action

diff --git a/.github/workflows/format-and-lint.yaml b/.github/workflows/format-and-lint.yaml
--- a/.github/workflows/format-and-lint.yaml
+++ b/.github/workflows/format-and-lint.yaml
@@ -2,7 +2,6 @@ name: Format, Lint, Type-Check, and Test
 
 on:
   pull_request:
-  push:
 
 permissions:
   contents: write
@@ -34,7 +33,7 @@ jobs:
           node-version: ${{ env.NODE_VERSION }}
 
       - name: Install dependencies
-        run: npm ci
+        run: npm install
 
       - name: Run ${{ matrix.task }}
         id: run-task
@@ -62,8 +61,50 @@ jobs:
           node-version: ${{ env.NODE_VERSION }}
 
       - name: Install dependencies
-        run: npm ci
+        run: npm install
 
       - name: Run Tests
         run: npm run ci:test
 
+  comment:
+    runs-on: ubuntu-latest
+    needs: [checks, test]
+    if: github.event_name == 'pull_request'
+    steps:
+      - name: Check for failures
+        id: check-failures
+        run: |
+          FAILURES=false
+          if [ "${{ needs.checks.outputs.format_result }}" == "failure" ]; then
+            echo "Format check failed"
+            FAILURES=true
+          fi
+          if [ "${{ needs.checks.outputs.lint_result }}" == "failure" ]; then
+            echo "Lint check failed"
+            FAILURES=true
+          fi
+          if [ "${{ needs.checks.outputs.type_check_result }}" == "failure" ]; then
+            echo "Type-check failed"
+            FAILURES=true
+          fi
+          if [ "$FAILURES" == "true" ]; then
+            echo "One or more checks failed"
+            exit 1
+          fi
+
+      - name: Create comment
+        uses: peter-evans/create-or-update-comment@v2
+        with:
+          issue-number: ${{ github.event.pull_request.number }}
+          body: |
+            # Summary of Format, Lint, Type-Check, and Test Results
+            | Job Name | Status | Link logs |
+            | --- | --- | --- |
+            | Format Check | ${{ needs.checks.outputs.format_result }} | ${{ job_logs_url('checks') }} |
+            | Lint Check | ${{ needs.checks.outputs.lint_result }} | ${{ job_logs_url('checks') }} |
+            | Type-Check | ${{ needs.checks.outputs.type_check_result }} | ${{ job_logs_url('checks') }} |
+            | Test | ${{ needs.test.result }} | ${{ job_logs_url('test') }} |
+
+      - name: Fail if there are failures
+        if: steps.check-failures.outputs.return-code == '1'
+        run: exit 1
